sudo: false
language: node_js
jobs:
  include:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "4"
    - node_js: "5"
    - node_js: "6"
    - node_js: "4"
      arch: ppc64le
    - node_js: "5"
      arch: ppc64le
    - node_js: "6"
      arch: ppc64le
